# _config.yml
title: Rettet den Bootsf端hrerschein
description: Eine Seite zur Unterst端tzung der Petition gegen die Abschaffung des amtlichen Sportbootf端hrerscheins
theme: jekyll-theme-cayman
url: "https://sbf-petition.de"
lang: de

# SEO
author: SBF Petition Initiative
keywords: Petition, Bootsf端hrerschein, SBF

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
